# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  setup-selective: selectiveci/setup-selective@0.1.1

jobs:
  test:
    parallelism: 4
    docker:
      - image: cimg/ruby:3.2
    steps:
      - setup-selective/init:
          actor: << pipeline.trigger_parameters.github_app.user_username >>
          run_id: << pipeline.id >>
          target_branch: main
      - checkout
      - run: bundle install
      - run: bundle exec selective rspec

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - test
