name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  selective:
    runs-on: ubuntu-latest
    name: Selective
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [4]
        ci_node_index: [0, 1, 2, 3]
    env:
      SELECTIVE_API_KEY: ${{ secrets.SELECTIVE_API_KEY }}
      SELECTIVE_RUN_ID: ${{ github.run_id }}
      SELECTIVE_RUN_ATTEMPT: ${{ github.run_attempt }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      SELECTIVE_RUNNER_ID: ${{ matrix.ci_node_index }}
      CLONE_PAT: ${{ secrets.CLONE_PAT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Run the default task
        run: bundle exec selective rspec

      - name: Store logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ./log/*.log
