name: Multi Ruby/RSpec Matrix

on:
  workflow_dispatch:

jobs:
  multi-ruby-rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} - RSpec ${{ matrix.gemfiles }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "head"
        gemfiles:
          - gemfiles/rspec_3.8.gemfile
          - gemfiles/rspec_3.9.gemfile
          - gemfiles/rspec_3.10.gemfile
          - gemfiles/rspec_3.11.gemfile
          - gemfiles/rspec_3.12.gemfile
        runners: [1, 2]

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfiles }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Setup Selective
        uses: selectiveci/setup-selective@v1
        with:
          api-key: ${{ secrets.SELECTIVE_API_KEY }}
          runner-id: ${{ matrix.runners }}

      - name: Run the default task
        env:
          SELECTIVE_RUN_ID: ${{ github.run_id }}-${{ matrix.ruby }}-${{ matrix.gemfiles }}
        run: bundle exec selective rspec
