name: Multi Ruby/RSpec Matrix

on:
  workflow_dispatch:

jobs:
  multi-ruby-rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} - RSpec ${{ matrix.gemfiles }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3.0-preview2"
          - "head"
        gemfiles:
          - gemfiles/rspec_3.8.gemfile
          - gemfiles/rspec_3.9.gemfile
          - gemfiles/rspec_3.10.gemfile
          - gemfiles/rspec_3.11.gemfile
          - gemfiles/rspec_3.12.gemfile
        runners: [1, 2]

    env:
      SELECTIVE_API_KEY: ${{ secrets.SELECTIVE_API_KEY }}
      BUNDLE_GEMFILE: ${{ matrix.gemfiles }}
      SELECTIVE_HOST: wss://app.selective.ci
      SELECTIVE_RUN_ID: ${{ github.run_id }}-${{ matrix.ruby }}-${{ matrix.gemfiles }}
      SELECTIVE_RUN_ATTEMPT: ${{ github.run_attempt }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      SELECTIVE_RUNNER_ID: ${{ matrix.ruby }}-${{ matrix.gemfiles }}-${{ matrix.runners }}
      CLONE_PAT: ${{ secrets.CLONE_PAT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Download Transport
        run: bin/get_transport

      - name: Run the default task
        run: bundle exec selective rspec
